name: my-workflow
on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job 1, step 1"
  job_2:
    runs-on: ubuntu-latest
    # needs: job_1
    steps:
      - name: Step 1
        run: echo "This is job 2, step 1"
      - name: Step 2
        run: echo "This is job 2, step 2"