name: my-workflow
on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job 1, step 1"
      - name: Step 2
        run: echo "This is job 1, step 2"
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: fail-step
        run: |
          echo "step going to fail!"
          exit 1
      - name: error message
        run: echo "failed!"
  job_3:
    runs-on: ubuntu-latest
    needs: job_2
    steps:
      - name: Step 1
        run: echo "This is job 3, step 1"